### ISSUE TITLE
还没实现内网穿透吗

### ISSUE THREAD

**Issue by Will-yc** [fzdwx/sky#37]
还没实现内网穿透吗，还是我没看懂该咋用才能实现内网穿透

**Comment by fzdwx** [comment]
不是这个项目。

可以看这个： https://github.com/fzdwx/burst

**Comment by Will-yc** [comment]
看到了，可以看到java和go的两个项目，想问有啥区别吗，我更熟悉java，go基本上没用过

**Comment by Will-yc** [comment]
有没有服务端是java的，然后客户端是go的

**Comment by fzdwx** [comment]
> 有没有服务端是java的，然后客户端是go的

java 版的就是这样的

**Comment by fzdwx** [comment]
> 看到了，可以看到java和go的两个项目，想问有啥区别吗，我更熟悉java，go基本上没用过

没什么区别，当时我主要是想熟悉一下 go 的语法，然后就全部用 go 写了一遍。

**Comment by fzdwx** [comment]
后面就由于各种原因，只把一些基础功能实现了，就没写了。

**Comment by Will-yc** [comment]
现在还是添加一个代理，就需要监听一个端口，还是一个端口可以处理所有的代理

**Comment by fzdwx** [comment]
> 现在还是添加一个代理，就需要监听一个端口，还是一个端口可以处理所有的代理

java 版本里面支持 HTTP 的可以一个端口处理所有的，主要原理是根据请求头中的`host`等字段来路由到指定的节点。

但是如果是一个 raw 的 TCP 连接，一个未知的协议，就做不到区分，所以不能共用一个端口。

**Comment by Will-yc** [comment]
方便问下有没有go项目的环境配置指南

**Comment by fzdwx** [comment]
> 方便问下有没有go项目的环境配置指南

不需要配什么，把 go 安好就好了。

**Comment by Will-yc** [comment]
项目都跑起来了，没有后台可视化页面吗，有点不知道怎么使用

**Comment by fzdwx** [comment]
https://github.com/fzdwx/burst/blob/java/doc/quick_start.md

可能有点复杂，不知道那时候是怎么想的，还搞 API，注册登陆那一套。。

**Comment by Will-yc** [comment]
就想要这样的，这轮子造的太好了

**Comment by Will-yc** [comment]
[https://user-images.githubusercontent.com/65269574/174085209-b9360ab9-bcd0-4e30-be0d-17018b058bc8.png](url)
这俩端口不能固定吗

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/201871167-4abe0c92-bf87-44f9-acab-23321470fc6e.png)
这俩端口都是404，不能固定吗

**Comment by fzdwx** [comment]
> [https://user-images.githubusercontent.com/65269574/174085209-b9360ab9-bcd0-4e30-be0d-17018b058bc8.png](url) 这俩端口不能固定吗

服务端端口的是随机的，客户端的端口就是你指定的:
![image](https://user-images.githubusercontent.com/65269574/201871166-0dcaa207-207f-4526-8bab-579ac38f4e00.png)

为什么服务端暴露的端口不指定：

> 这个其实可以指定，改下代码就可以了。
> 当时想的是如果有多个用户指定了同一个端口的情况，所以改成了随机监听。

**Comment by Will-yc** [comment]
服务端一个端口监听所有的token用户是怎么配置的

**Comment by fzdwx** [comment]
> 服务端一个端口监听所有的token用户是怎么配置的

什么意思？

**Comment by Will-yc** [comment]
因为现在每个监听都会启动一个服务端的端口，服务端的端口最多也就6万个，能不能一个端口处理所有的代理，有用户注册的话，也不会新开端口，有点像多路复用

**Comment by fzdwx** [comment]
HTTP 类型的可以，具体原因前面已经回复了。然后使用方法：

![image](https://user-images.githubusercontent.com/65269574/201873062-5b6078d9-aa42-4b7f-9b73-c6c3909a7b42.png)

这个`customDomain`就对应`host`中的地址

**Comment by Will-yc** [comment]
第一个代理已经OK了，研究研究代码去

**Comment by Will-yc** [comment]
> HTTP 类型的可以，具体原因前面已经回复了。然后使用方法：
> 
> ![image](https://user-images.githubusercontent.com/65269574/201873062-5b6078d9-aa42-4b7f-9b73-c6c3909a7b42.png)
> 
> 这个`customDomain`就对应`host`中的地址

你这个在哪里看的

**Comment by fzdwx** [comment]
https://github.com/fzdwx/sky/issues/37#issuecomment-1314958474 点这个链接，有个 API 文档。

**Comment by Will-yc** [comment]
go的客户端像要打印每一个请求，有没有开启的地方

**Comment by fzdwx** [comment]
每一个请求的内容这个没有，只是打印了一下每个数据包的长度

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/201877138-426460bd-ae76-42f3-b218-ed49add2a36e.png)
我这边什么都没有打印，就想打印一个请求的路径，比如 /   /xx/xx   /sd.html 之类的，然后还有一个http的code

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/201877752-2da65e7f-db29-41ba-b9b6-acf4511d3396.png)
是在这里添加打印吗

**Comment by fzdwx** [comment]
> ![image](https://user-images.githubusercontent.com/21304095/201877138-426460bd-ae76-42f3-b218-ed49add2a36e.png) 我这边什么都没有打印，就想打印一个请求的路径，比如 / /xx/xx /sd.html 之类的，然后还有一个http的code

客户端启动的时候加 `-d`，然后打印路径应该不行。

**Comment by fzdwx** [comment]
> ![image](https://user-images.githubusercontent.com/21304095/201877752-2da65e7f-db29-41ba-b9b6-acf4511d3396.png) 是在这里添加打印吗

不是

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/202096782-a3f4e825-95e6-495b-acfa-0ce6f5cf3525.png)
这个里面有办法输出访问的URL吗

**Comment by fzdwx** [comment]
> ![image](https://user-images.githubusercontent.com/21304095/202096782-a3f4e825-95e6-495b-acfa-0ce6f5cf3525.png) 这个里面有办法输出访问的URL吗

要解析

**Comment by Will-yc** [comment]
大佬，这个方便出一个吗，go第一次用，还不熟悉语法

**Comment by fzdwx** [comment]
> 大佬，这个方便出一个吗，go第一次用，还不熟悉语法

跟 java 没什么区别，就是要写解析协议的代码。

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/202641886-6601f88b-95e1-45e8-8e72-397a92bb6d9f.png)
springboot项目配置了server.servlet.context-path，但是启动的时候，这个值却一直没用，有没有办法搞定

**Comment by fzdwx** [comment]
> ![image](https://user-images.githubusercontent.com/21304095/202641886-6601f88b-95e1-45e8-8e72-397a92bb6d9f.png) springboot项目配置了server.servlet.context-path，但是启动的时候，这个值却一直没用，有没有办法搞定

你看下代码，这个值我没用。你可以用 nginx。

**Comment by Will-yc** [comment]
因为服务器有其他项目，想给10086端口配置一个统一路径，但是Springboot提供的这个值，却不生效··

**Comment by fzdwx** [comment]
> 因为服务器有其他项目，想给10086端口配置一个统一路径，但是Springboot提供的这个值，却不生效··

nginx 根据那个前缀转发不行吗，或者你给所有的请求地址加一个前缀也是一样的效果

**Comment by Will-yc** [comment]
项目里面都是 port/*  直接访问接口了，nginx转发都是根据前缀转发的，nginx的alias主要是物理路径的别称，端口转发好像不太行

**Comment by Will-yc** [comment]
主要项目还得有统一前缀

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/202650681-2cd04c07-971c-4ff9-b846-052cd0f300f5.png)

这样不就可以了吗？

**Comment by fzdwx** [comment]
这个 qwe 不就是一个前缀吗

**Comment by fzdwx** [comment]
nginx 不能根据请求地址转发？

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/202651039-9e5ff109-5169-4184-957f-626cadca711b.png)
看到了，sky项目里面把server的配置给重置了

**Comment by Will-yc** [comment]
> 这个 qwe 不就是一个前缀吗

这种方式是可以的，一般就是习惯的用springboot提供的了，突然遇到不生效了，就查看了一下

**Comment by fzdwx** [comment]
> > 这个 qwe 不就是一个前缀吗
> 
> 这种方式是可以的，一般就是习惯的用springboot提供的了，突然遇到不生效了，就查看了一下

不生效肯定是我没实现。。

加也很简单，你可以试试。

**Comment by Will-yc** [comment]
嗯嗯，找的地方了，就能改了

**Comment by Will-yc** [comment]
你这写的太深了

**Comment by fzdwx** [comment]
就那个 starter 里面的 dispatch 就是吧？

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/202653568-2580a90f-8fd2-42ee-bb31-eaa0fefd08be.png)

**Comment by fzdwx** [comment]
就这里，判断 startWith 然后替换为空

**Comment by Will-yc** [comment]
一般不会有人动这些东西的，我这就算改了，还得自己搭建私服，才能使用的

**Comment by Will-yc** [comment]
还有springboot中resources里面的static文件访问的，要改的话，还是麻烦事，相当于阉割了springboot的一些配置
