### ISSUE TITLE
如何注册服务中心

### ISSUE THREAD

**Issue by ChenMuChao** [fzdwx/sky#38]
老哥你是如何注册到服务中心的？

**Comment by fzdwx** [comment]
我这个项目吗？还是哪个？

**Comment by ChenMuChao** [comment]
是指您这个项目，请教下您是怎么发布事件的

**Comment by fzdwx** [comment]
我记得 nacos 是监听一个 web 容器启动的事件来启动 nacos 注册流程的

你看这个类吧 https://github.com/fzdwx/sky/blob/main/sky-http-springboot-starter/src/main/java/sky/SkyWebServerAutoConfiguration.java#L68

**Comment by ChenMuChao** [comment]
是的，牛逼

**Comment by ChenMuChao** [comment]
没搞懂是在哪里发布了容器启动的事件？可以加大佬个微信吗？

**Comment by fzdwx** [comment]
13789983260

marco ***@***.***> 于2024年4月3日周三 11:56写道：
